  TLSG3424-SNMP-MIB DEFINITIONS ::= BEGIN

         IMPORTS
            MODULE-IDENTITY
          	  	         	FROM SNMPv2-SMI
            tlsg3424	          
          	  	          FROM TPLINK; 
          	  	          
          	 
	    snmpControl MODULE-IDENTITY
	    LAST-UPDATED    "2009081900Z"
	    ORGANIZATION    "TPLINK"
	    CONTACT-INFO    "www.tplink.com.cn"
	    DESCRIPTION
	             "Private MIB for snmp config."
	    REVISION        "2009081900Z"
	    DESCRIPTION
	            "Initial version of this MIB module."
	    ::= { tlsg3424 9 }
	    
		snmpNotifyCtrl	OBJECT IDENTIFIER ::= {snmpControl 1}
		snmpRmon	OBJECT IDENTIFIER ::= {snmpControl 2}
  	
END

