       TLSG3424-SNMPRMON-MIB DEFINITIONS ::= BEGIN

          IMPORTS
             
             MODULE-IDENTITY
          	  	         	FROM SNMPv2-SMI
              snmpRmon	          
          	  	          	FROM TLSG3424-SNMP-MIB; 

          snmpRmonHistoryCtrl      	OBJECT IDENTIFIER ::= {snmpRmon 1}
          snmpRmonEventCtrl 		OBJECT IDENTIFIER ::= {snmpRmon 2}
	  snmpRmonAlarmCtrl		OBJECT IDENTIFIER ::= {snmpRmon 3}
  
          END